-- SmartTrack Inventory System - Sample Data Initialization
-- Run this after the application creates the schema

USE smarttrack_inventory;

-- Sample Products (if not already created by Hibernate)
INSERT INTO products (name, description, category_id, supplier_id, sku, unit, min_stock_level, created_at, updated_at) 
SELECT 'Fresh Milk 1L', 'DairyFarm Inc.', 1, 1, 'PK-2023-001', 'Liter', 10, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'PK-2023-001');

INSERT INTO products (name, description, category_id, supplier_id, sku, unit, min_stock_level, created_at, updated_at) 
SELECT 'Pain Relief Tablets', 'MediCaps', 2, 2, 'PP-102-X', 'Box', 50, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'PP-102-X');

INSERT INTO products (name, description, category_id, supplier_id, sku, unit, min_stock_level, created_at, updated_at) 
SELECT 'Cheddar Cheese', 'DairyFarm Inc.', 1, 1, 'OP-221', 'Pack', 20, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'OP-221');

INSERT INTO products (name, description, category_id, supplier_id, sku, unit, min_stock_level, created_at, updated_at) 
SELECT 'Face Moisturizer', 'BeautyCo', 3, 3, 'CS-191', 'Bottle', 30, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'CS-191');

INSERT INTO products (name, description, category_id, supplier_id, sku, unit, min_stock_level, created_at, updated_at) 
SELECT 'Wireless Mouse', 'TechWorld', 4, 3, 'EL-555', 'Unit', 50, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM products WHERE sku = 'EL-555');

-- Sample Inventory Batches
INSERT INTO inventory_batches (product_id, batch_number, quantity, unit_price, manufacturing_date, expiry_date, status, storage_location, created_at, updated_at)
SELECT 1, '#PK-2023-001', 45, 2.50, '2025-11-01', '2025-12-11', 'NEAR_EXPIRY', 'Cold Storage A1', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM inventory_batches WHERE batch_number = '#PK-2023-001');

INSERT INTO inventory_batches (product_id, batch_number, quantity, unit_price, manufacturing_date, expiry_date, status, storage_location, created_at, updated_at)
SELECT 2, '#PP-102-X', 120, 8.99, '2025-01-15', '2025-12-31', 'NEAR_EXPIRY', 'Pharmacy Vault B3', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM inventory_batches WHERE batch_number = '#PP-102-X');

INSERT INTO inventory_batches (product_id, batch_number, quantity, unit_price, manufacturing_date, expiry_date, status, storage_location, created_at, updated_at)
SELECT 3, '#OP-221', 12, 5.75, '2025-11-20', '2025-12-02', 'EXPIRED', 'Cold Storage A2', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM inventory_batches WHERE batch_number = '#OP-221');

INSERT INTO inventory_batches (product_id, batch_number, quantity, unit_price, manufacturing_date, expiry_date, status, storage_location, created_at, updated_at)
SELECT 4, '#CS-191', 8, 15.99, '2024-11-20', '2026-11-20', 'GOOD', 'Cosmetics Shelf C2', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM inventory_batches WHERE batch_number = '#CS-191');

INSERT INTO inventory_batches (product_id, batch_number, quantity, unit_price, manufacturing_date, expiry_date, status, storage_location, created_at, updated_at)
SELECT 5, '#EL-555', 50, 12.50, '2025-06-01', '2029-06-10', 'GOOD', 'Electronics Warehouse D1', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM inventory_batches WHERE batch_number = '#EL-555');

-- Alerts (optional - can be auto-generated by scheduled jobs)
INSERT INTO alerts (batch_id, alert_type, severity, message, is_acknowledged, created_at)
SELECT 1, 'EXPIRY', 'WARNING', 'Fresh Milk 1L (Batch #PK-2023-001) expiring within 30 days', FALSE, NOW()
WHERE NOT EXISTS (SELECT 1 FROM alerts WHERE batch_id = 1);

INSERT INTO alerts (batch_id, alert_type, severity, message, is_acknowledged, created_at)
SELECT 3, 'EXPIRY', 'CRITICAL', 'Cheddar Cheese (Batch #OP-221) has expired - requires immediate disposal', FALSE, NOW()
WHERE NOT EXISTS (SELECT 1 FROM alerts WHERE batch_id = 3);

COMMIT;

SELECT 'Sample data initialized successfully!' AS Status;
